### ISSUE TITLE
didt work, no communication

### ISSUE THREAD

**Issue by xnfctn** [ifsc-saojose/FPS_GT511C3_DUE_MEGA#1]
Dear Coders,

firstofall thank you guys for your work!

i have a arduino MEGA and a FPS. i wired both like in [here ](https://learn.sparkfun.com/tutorials/fingerprint-scanner-hookup-guide)"2.) Option 1", so i used a LLC.
When i test via softwareserial it works but not reliable. So i want to use your code.

i connected the FPS RX to Arduino's TX3, and the FPS TX to Arduino's RX3.
i used the blink sketch and did edit like follwing:

FPS_GT511C3 fps(**14, 15**);

void setup()
{
  Serial.begin(9600);
	Serial3.begin(9600);
	fps.UseSerialDebug = true; // so you can see the messages in the serial debug screen
	fps.Open();
}

in the monitor i only got

FPS - Open
FPS - SEND: "55 AA 01 00 00 00 00 00 01 00 01 01"

but no response. any ideas what i did wrong?

**Comment by cleberjamaral** [comment]
Hi,
It has some time I don't use this module. I guess it is everything right with your code, I think it doesn't send nothing after open communication command (this one you sent).
Try the complete examples, firt using blink, if it blinks you have this feedback (the serial is working both ways), if it works is a good way to start. Later try enroll, where for sure you must receive some messages from the module.
To say the truth, my experience with this module was not good, at least my unit was too sensible about light (to reduce this bad behaviour I have used a black cloth covering the sensor) and the feedbacks are not enought enlightening.
Good luck!

**Comment by xnfctn** [comment]
Thank you, I didnt get the mega to work. I Switched to uno and Now it's ok
